<?php

/**
 * @file
 * Contains px_web_graph.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function px_web_graph_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the px_web_graph module.
    case 'help.page.px_web_graph':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for px web for Hagstovan') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
 /*
function px_web_graph_theme() {
  return [
    'px_web_graph' => [
      'render element' => 'children',
    ],
  ];
}
*/