<?php

/**
 * @file
 * Contains px_web.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function px_web_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the px_web module.
    case 'help.page.px_web':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for px web for Hagstovan') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
/*


function px_web_theme() {

  return [
    'px_web' => [
      'render element' => 'children',
    ],
  ];
}
*/